lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

#commands to generate private and public keys
# openssl genrsa -out config/jwt/private.pem -aes256 4096
# openssl rsa -pubout -in config/jwt/private.pem -out config/jwt/public.pem