version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../project:/var/www
      - ./php-fpm/php.local.ini:/usr/local/etc/php/conf.d/php.local.ini
    environment:
      PHP_IDE_CONFIG: "serverName=docker-php"

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../project:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  mailcatcher:
    image: jeanberu/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080